### ISSUE TITLE
Iconography vs photos

### ISSUE THREAD

**Issue by axrez** [SOSChildrensVillages/HackXmas2019#7]
What kind of experience does caretakers have with iconography? We could imagine different cultures respond differently to the same icons. Have you thought about using images instead?

**Comment by strabu** [comment]
That's an interesting topic but we haven't thought about using images.
We don't have a male/female icon (the mars and venus symbol) and no red/blue for girls/boys because of such considerations.
The icons we have so far seem to be OK.
We have RTL-languaes eg. hebrew and arabic but don't flip the menu and icons to the other side, that's fine for them.
